# Generated by Django 2.0.5 on 2019-12-05 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='humidity',
        ),
    ]
