# Generated by Django 2.0.5 on 2019-12-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_log_humidity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='temperature',
            field=models.FloatField(blank=True, verbose_name='混雑度'),
        ),
    ]
