# Generated by Django 2.0.5 on 2019-12-18 12:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191205_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録時間'),
        ),
    ]
